[commandDescriptions]
  about      = "Information about the bot"
  choose     = "Picks from a selection menu"
  discordfm  = "Plays music from discord.fm playlists"
  dump       = "Outputs the music queue as a json string"
  help       = "Shows command help"
  invite     = "Adds the bot to your server"
  jump       = "Skips to a time in the current song"
  move       = "Moves the bot to a different voice channel"
  nowplaying = "Shows the current song"
  pause      = "Pauses & resumes the song"
  play       = "Adds a song to the queue and begins playing"
  queue      = "Shows the song queue"
  radio      = "Streams radio stations"
  remove     = "Remove a radio"
  reorder    = "Changes the position of a song in the queue"
  repeat     = "Loops the current song"
  restart    = "Plays a song from the beginning"
  search     = "Searches for a song on youtube"
  shuffle    = "Shuffles the song queue"
  skip       = "Plays the next song in the queue"
  stop       = "Stops playing and leaves the voice channel"
  volume     = "Changes the music volume"

[radioStations]
  "89.O RTL"              = "http://fhhalle.hoerradar.de/890rtl-live-mp3-mq"
  "ABC News"              = "http://www.abc.net.au/res/streaming/audio/mp3/news_radio.pls"
  "ABC Double J"          = "http://www.abc.net.au/res/streaming/audio/aac/dig_music.pls"
  "ABC Triple J"          = "http://www.abc.net.au/res/streaming/audio/mp3/triplej.pls"
  "ABC Brisbane"          = "http://www.abc.net.au/res/streaming/audio/mp3/local_brisbane.pls"
  "Absolute Classic Rock" = "http://icy-e-bab-04-cr.sharp-stream.com/absoluteclassicrock.mp3.m3u"
  "Absolute Radio"        = "http://icy-e-bab-09-boh.sharp-stream.com/absoluteradio.mp3"
  "Absolute Radio 80s"    = "http://icy-e-bab-04-cr.sharp-stream.com/absolute80s.mp3.m3u"
  "Anime Radio UK"        = "http://149.255.59.164/proxy/animerad?mp=/stream"
  "Animes Station"        = "https://streaming.radionomy.com/Animes-Station"
  "AniSonFM"              = "http://pool.anison.fm:9000/AniSonFM(320)"
  "AntyRadio"             = "http://ant-waw-02.cdn.eurozet.pl:8602/;stream"
  "AvtoRadio"             = "http://ic7.101.ru:8000/v3_1"
  "BBC 1Xtra"             = "http://www.listenlive.eu/bbc1xtra.m3u"
  "BBC Asian Network"     = "http://www.listenlive.eu/bbcasian.m3u"
  "BBC Radio 1"           = "http://www.listenlive.eu/bbcradio1.m3u"
  "BBC Radio 2"           = "http://www.listenlive.eu/bbcradio2.m3u"
  "BBC Radio 3"           = "http://www.listenlive.eu/bbcradio3.m3u"
  "BBC Radio 4"           = "http://www.listenlive.eu/bbcradio4.m3u"
  "BBC Radio 5 Live"      = "http://www.listenlive.eu/bbc5live.m3u"
  "BBC Radio Wales"       = "http://www.radiofeeds.co.uk/bbcradiowales.pls"
  "BridgeFM"              = "http://icy-e-03-boh.sharp-stream.com/tcbridge.mp3"
  "CapitalFM Liverpool"   = "http://media-ice.musicradio.com/CapitalLiverpoolMP3.m3u"
  "CapitalFM South Wales" = "http://media-ice.musicradio.com/CapitalSouthWalesMP3"
  "CapitalFM XTRA London" = "http://media-ice.musicradio.com/CapitalXTRALondonMP3"
  "Cima 100"              = "http://www.surfmusic.de/m3u/cima-100-fm,3447.m3u"
  "ClassicFM"             = "http://media-ice.musicradio.com/ClassicFMMP3"
  "CKIXFM"                = "http://69.65.38.214/CKIXFM-MP3"
  "Derman Gibi Radyo"     = "http://yayin3.canlitv.com:9050"
  "Drive Radio"           = "http://streaming.radionomy.com/DRIVE"
  "EnergyFM"              = "http://ic8.101.ru:8000/v1_1"
  "EuropaPlus"            = "http://ep256.hostingradio.ru:8052/europaplus256.mp3"
  "EHR"                   = "http://stream.europeanhitradio.com:8000/ehr.mp3"
  "EHR Fresh"             = "http://stream.europeanhitradio.com:8000/Stream_05.mp3"
  "FalloutFM"             = "http://46.101.243.245:8000/falloutfm1.ogg"
  "FFN"                   = "http://138.201.251.246/ffn_192"
  "FlaixFM"               = "http://radiostream.flaixfm.cat:8000"
  "Forth 1"               = "http://icy-e-bl-05-cr.sharp-stream.com/forth1.mp3"
  "FutureGeneration"      = "http://37.1.144.106:9001/;stream.mp3"
  "GGRadio.net"           = "http://sv.ggradio.net:8000/stream"
  "Happy Christmas Radio" = "http://streaming.radionomy.com/HappyChristmasradio"
  "Hard FM Estonia"       = "http://shaincast.caster.fm:44230/listen.mp3"
  "heat Radio"            = "http://icy-e-bl-03-gos.sharp-stream.com/heat.mp3"
  "Heart"                 = "http://media-ice.musicradio.com/HeartSouthWalesMP3"
  "Hive365"               = "http://stream.hive365.co.uk:8088/live"
  "Hot 97"                = "http://17793.live.streamtheworld.com:3690/WQHTFM_SC"
  "ILoveRadio 1"          = "http://stream06.iloveradio.de/iloveradio1.mp3"
  "ILoveRadio 2"          = "http://stream06.iloveradio.de/iloveradio2.mp3"
  "JackFM Oxfordshire"    = "http://19093.live.streamtheworld.com/JACK_FM.mp3"
  "JapanFM"               = "http://radio.japanfm.fr/japan"
  "Kerrang!"              = "http://icy-e-bl-04-cr.sharp-stream.com:8000/kerrang.mp3"
  "KissFM"                = "http://icy-e-ba-09-boh.sharp-stream.com/kissnational.mp3"
  "Kiss Fresh"            = "http://icy-e-bl-06-cr.sharp-stream.com:8000/kissfresh.mp3"
  "Kisstory"              = "http://icy-e-bl-06-cr.sharp-stream.com:8000/kisstory.mp3"
  "KLIK FM"               = "http://111.gr:8042/;&type=sound"
  "Los40"                 = "http://19113.live.streamtheworld.com/LOS40.mp3"
  "M-1"                   = "http://stream.m-1.fm/M-1aacp"
  "Magic"                 = "http://icy-e-bz-02-gos.sharp-stream.com/magicnational.mp3"
  "Magic Chilled"         = "http://icy-e-bz-04-cr.sharp-stream.com/magicchilled.mp3"
  "Mellow Magic"          = "http://icy-e-bz-07-boh.sharp-stream.com/magicmellow.mp3"
  "MixFM"                 = "http://mixmp3.crossradio.com.br:1102/live"
  "Nation Radio"          = "http://icy-e-03-boh.sharp-stream.com/tcnation.mp3"
  "NJOY Radio"            = "http://46.10.150.243/njoy.mp3"
  "NonStopPlay"           = "http://www.nonstopplay.com/site/media/pls/midband.pls"
  "NRJ"                   = "http://stream.p4.no/nrj_mp3_mq"
  "NRK mP3"               = "http://nrk-mms-live.online.no/nrk_radio_mp3_aac_h"
  "Nova 919"              = "http://streaming.novaentertainment.com.au/nova919"
  "Otvoreni"              = "http://50.7.130.2:13014/stream"
  "P3"                    = "http://live-icy.gss.dr.dk/A/A05L.mp3"
  "Pirate Station"        = "http://air.radiorecord.ru:8102/ps_320"
  "Play Radio RS"         = "http://stream.playradio.rs:8001/play.mp3"
  "PowerFM"               = "http://icast.powergroup.com.tr/PowerFM/mpeg/128/home"
  "PowerHitRadio"         = "http://power-stream.data.lt:8000/PHR.mp3"
  "PowerTurk"             = "http://195.142.3.82/power/PowerTurk_mpeg_128_home/icecast.audio"
  "Qmusic"                = "http://icecast-qmusic.cdp.triple-it.nl/Qmusic_nl_live_96.mp3"
  "Raw FM"                = "https://rawfm.com.au/stream/playlists/160kbitMP3.pls"
  "R101"                  = "http://se-to1-6.se.wradio.msf.ticdn.it/r101_mp3"
  "Radio 538"             = "http://vip-icecast.538.lw.triple-it.nl/RADIO538_MP3"
  "Radio AS FM"           = "http://radioas.kbcnet.rs:8045/listen.pls"
  "Radio Banovina"        = "http://www.radio-banovina.hr/popup/playlist.php?name=listen.pls"
  "Radio Beograd"         = "http://rts.ipradio.rs:8006/;694070477696226stream.nsv"
  "Radio City"            = "http://icy-e-bl-09-boh.sharp-stream.com/city.mp3"
  "Radio Disney"          = "http://radio.domint.net:8026/"
  "Radio Flaixbac"        = "http://radiostream.radioflaixbac.cat:8004/listen.pls"
  "Radio FEST"            = "http://primary.moodyradiostream.org/radiofest"
  "Radio Hamburg"         = "http://stream.radiohamburg.de/rhh-live/mp3-128/webplayer/9579617252927166/"
  "Radio Nova Era"        = "http://centova.radios.pt:9478/stream"
  "Radio Record"          = "http://air.radiorecord.ru:8101/rr_320"
  "Radio Severozapad"     = "http://stream.rsmedia.net:8007/severozapad"
  "Radyo Fenomen"         = "http://185.28.3.4/fenomen/fenomenweb_mpeg_128_home/icecast.audio"
  "Radio Veronica"        = "http://8543.live.streamtheworld.com/VERONICACMP3"
  "Record Dance Radio"    = "http://air.radiorecord.ru:805/rr_320"
  "Record Hardstyle"      = "http://air.radiorecord.ru:8102/teo_320"
  "RMF Maxxx"             = "http://195.150.20.242:8000/rmf_maxxx"
  "Rock FM"               = "http://icy-e-bz-08-boh.sharp-stream.com/rock.mp3"
  "Rock FM 2"             = "http://icy-e-bz-04-cr.sharp-stream.com/magic999.mp3"
  "Rock FM 3"             = "http://icy-e-bz-08-boh.sharp-stream.com/rock3.mp3"
  "SBS Pop Asia"          = "http://shoutcast.sbs.com.au/SBSPopAsia"
  "Simulator Radio"       = "http://listen.simulatorradio.com:8000/stream"
  "Slam"                  = "http://stream.slam.nl/slam"
  "Smooth Radio"          = "http://media-ice.musicradio.com/SmoothSouthWalesMP3"
  "South America Memes"   = "http://stm16.adcast.com.br:24976/stream/1/"
  "Sunshine Live"         = "http://sunshinelive.hoerradar.de/sunshinelive-live-mp3-hq"
  "SwanseaSound"          = "http://gbradio.cdn.tibus.net/SWASS"
  "SWR3"                  = "https://swr-mp3-m-swr3.akacast.akamaistream.net/7/720/137136/v1/gnl.akacast.akamaistream.net/swr-mp3-m-swr3"
  "The Breeze"            = "http://stream5.radiomonitor.com/Breeze-Bristol-128"
  "The Hits Radio"        = "http://icy-e-bl-04-cr.sharp-stream.com/hits.mp3"
  "The UK 1940s"          = "http://149.255.59.164:8063/1"
  "TheWave"               = "http://gbradio.cdn.tibus.net/SWAWave"
  "TSF"                   = "http://tsfdirecto.tsf.pt/tsfdirecto.mp3"
  "UK RAW Radio"          = "http://37.187.90.201:8014/ukrawbruv.mp3"
  "Virgin Radio"          = "http://vr-live-mp3-128.scdn.arkena.com/virginradio.mp3"
  "Wild Soul Child Radio" = "http://14123.live.streamtheworld.com/SAM04AAC213_SC"
  "Yasmin Radio"          = "http://www.internet-radio.com/servers/tools/playlistgenerator/?u=http://uk1.internet-radio.com:8130/listen.pls&t=.m3u"
